from ecdsa import SigningKey, SECP256k1, BadSignatureError
import hashlib

BASE = r"C:\Users\jayja\OneDrive\Desktop\PUF\PUF - HACKATHON\shared"

def derive_keys(hex_key):
    b = bytes.fromhex(hex_key)
    priv = hashlib.sha256(b).digest()
    sk = SigningKey.from_string(priv, curve=SECP256k1)
    return sk, sk.verifying_key

def banner(t):
    print("\n" + "="*65)
    print("  " + t)
    print("="*65)

banner("PUF-Pay : Two-Chip Hardware Security Demonstration")
print("  Chip A key and Chip B key BOTH generated by real RTL simulation")
print("  (256 ring oscillators each, different CHIP_SEED)")

# ---------------------------------------------------------
# STEP 1: Read BOTH keys - generated by actual Vivado hardware
# ---------------------------------------------------------
with open(f"{BASE}\\puf_key_chipA.txt") as f:
    keyA_hex = f.read().strip()

with open(f"{BASE}\\puf_key_chipB.txt") as f:
    keyB_hex = f.read().strip()

banner("STEP 1 : KEYS FROM REAL HARDWARE SIMULATION")
print("Chip A (legitimate device) key :", keyA_hex)
print("Chip B (attacker's clone)  key :", keyB_hex)
print("Keys identical?                :", keyA_hex == keyB_hex)

skA, vkA = derive_keys(keyA_hex)
skB, vkB = derive_keys(keyB_hex)

# ---------------------------------------------------------
# STEP 2: Chip A enrolls with the bank (one-time registration)
# ---------------------------------------------------------
banner("STEP 2 : CHIP A ENROLLS WITH BANK")
print("Chip A sends its PUBLIC key to bank (private key stays on chip)")
bank_stored_public_key = vkA
print("Bank database now stores: Chip A's public key ->", 
      bank_stored_public_key.to_string().hex()[:40], "...")

# ---------------------------------------------------------
# STEP 3: Chip A makes a LEGITIMATE payment
# ---------------------------------------------------------
banner("STEP 3 : CHIP A - LEGITIMATE PAYMENT")
txn = "PAY 500 TO MERCHANT_X | TS 2026-08-16"
print("Transaction:", txn)
sigA = skA.sign(txn.encode())
print("Chip A signs with its regenerated private key...")
try:
    bank_stored_public_key.verify(sigA, txn.encode())
    print("Bank verify : ✅ APPROVED (Chip A is genuine)")
except BadSignatureError:
    print("Bank verify : ❌ REJECTED (unexpected!)")

# ---------------------------------------------------------
# STEP 4: Chip B (attacker's cloned/different chip) tries to pay
#         pretending to be Chip A
# ---------------------------------------------------------
banner("STEP 4 : CHIP B (ATTACKER) ATTEMPTS SAME PAYMENT")
print("Attacker has a DIFFERENT physical chip (different silicon).")
print("Attacker signs the SAME transaction using Chip B's own key...")
sigB = skB.sign(txn.encode())

print("\nBank checks signature against Chip A's REGISTERED public key")
try:
    bank_stored_public_key.verify(sigB, txn.encode())
    print("Bank verify : ❌ UNEXPECTED APPROVAL (security broken!)")
except BadSignatureError:
    print("Bank verify : ✅ REJECTED")
    print(">> Chip B's silicon is different -> different key -> invalid signature")

# ---------------------------------------------------------
# STEP 5: Summary
# ---------------------------------------------------------
banner("SECURITY SUMMARY")
print("✅ Chip A key and Chip B key both generated by REAL RTL hardware")
print("✅ Zero manually-typed/hardcoded keys used in this demo")
print("✅ Same architecture, different silicon (CHIP_SEED) -> different key")
print("✅ Bank only ever sees public keys, never private keys")
print("✅ Cloned/different chip cannot forge a valid signature")
print("\n  PUF-Pay hardware-rooted authentication PROVEN end-to-end.")